/* GENERATED by tools/gen_assets.py from the assets/ sources - do not edit. */

#ifndef SPP_ASSETS_H
#define SPP_ASSETS_H

#include <stdint.h>
#include "tiles.h"                 /* T_COUNT */

/* All of this lives in a switchable ROM bank: read it with the bank switched in
   (BANK(assets)); the engine copies what it needs at run time to RAM. */
#ifdef __SDCC
#include <gbdk/platform.h>
BANKREF_EXTERN(assets)
#endif

/* ---- world BG tileset (also used by the HUD window and menus) ---- */
#define BG_TILE_COUNT 149
#define BG_TILES_LO   128
#define BG_TILES_HI   21
extern const uint8_t bg_tiles[];
extern const uint8_t mt_tiles[T_COUNT][4];
extern const uint8_t mt_attr[T_COUNT][4];

/* font: ASCII -> BG tile number (unmapped -> TILE_BLANK) */
extern const uint8_t font_map[128];
#define TILE_BLANK 0

/* animated BG tiles: every ANIM_PERIOD frames, BG tile anim_tile[i] gets pattern
   anim_frames[i][f], f = 0..ANIM_FRAMES-1 */
#define ANIM_COUNT  8
#define ANIM_FRAMES 4
#define ANIM_PERIOD 8
extern const uint8_t anim_tile[ANIM_COUNT];
extern const uint8_t anim_frames[ANIM_COUNT][ANIM_FRAMES][16];

/* ---- sprites (8x16 OBJ mode): tile number of the top-left 8x16 object ---- */
#define SPR_TILE_COUNT 194
#define SPR_PS_STAND       0   /* 16x16 */
#define SPR_PS_WALK0       4   /* 16x16 */
#define SPR_PS_WALK1       8   /* 16x16 */
#define SPR_PS_WALK2      12   /* 16x16 */
#define SPR_PS_SKID       16   /* 16x16 */
#define SPR_PS_JUMP       20   /* 16x16 */
#define SPR_PS_DEAD       24   /* 16x16 */
#define SPR_PB_STAND      28   /* 16x32 */
#define SPR_PB_WALK0      36   /* 16x32 */
#define SPR_PB_WALK1      44   /* 16x32 */
#define SPR_PB_WALK2      52   /* 16x32 */
#define SPR_PB_SKID       60   /* 16x32 */
#define SPR_PB_JUMP       68   /* 16x32 */
#define SPR_PB_DUCK       76   /* 16x16 */
#define SPR_GLOOP         80   /* 16x16 */
#define SPR_GLOOP_FLAT    84   /* 16x16 */
#define SPR_DOME0         88   /* 16x32 */
#define SPR_DOME1         96   /* 16x32 */
#define SPR_SHELL        104   /* 16x16 */
#define SPR_SHELL_WAKE   108   /* 16x16 */
#define SPR_JET0         112   /* 8x16 */
#define SPR_JET1         114   /* 8x16 */
#define SPR_CHOMP0       116   /* 16x32 */
#define SPR_CHOMP1       124   /* 16x32 */
#define SPR_COMET        132   /* 16x16 */
#define SPR_PLANET       136   /* 16x16 */
#define SPR_BLASTER      140   /* 16x16 */
#define SPR_NOVA         144   /* 16x16 */
#define SPR_1UP          148   /* 16x16 */
#define SPR_COIN0        152   /* 8x16 */
#define SPR_COIN1        154   /* 8x16 */
#define SPR_COIN2        156   /* 8x16 */
#define SPR_SHOT         158   /* 8x16 */
#define SPR_PUFF         160   /* 8x16 */
#define SPR_SHARD        162   /* 8x16 */
#define SPR_FLAG         164   /* 16x16 */
#define SPR_BRICK        168   /* 16x16 */
#define SPR_USED         172   /* 16x16 */
#define SPR_N10          176   /* 8x16 */
#define SPR_N20          178   /* 8x16 */
#define SPR_N40          180   /* 8x16 */
#define SPR_N50          182   /* 8x16 */
#define SPR_N80          184   /* 8x16 */
#define SPR_N1U          186   /* 8x16 */
#define SPR_N0           188   /* 8x16 */
#define SPR_N00          190   /* 8x16 */
#define SPR_NP           192   /* 8x16 */
extern const uint8_t spr_tiles[];

/* ---- palettes ---- */
#define PAL_SKY      0
#define PAL_GROUND   1
#define PAL_BRICK    2
#define PAL_GOLD     3
#define PAL_TUBE     4
#define PAL_DECOR    5
#define PAL_HUD      6
#define PAL_POLE     7
#define OPAL_PETER   0
#define OPAL_BLASTER 1
#define OPAL_GREEN   2
#define OPAL_RED     3
#define OPAL_ITEM    4
#define OPAL_GOLD    5
#define OPAL_FX      6
#define OPAL_BLOCK   7
extern const uint16_t cgb_bg_pal[8][4];
extern const uint16_t cgb_obj_pal[8][4];
#define DMG_BGP  0xE4
#define DMG_OBP0 0xE4   /* Peter, enemies, items */
#define DMG_OBP1 0xD0   /* the blaster suit, flashing */

/* ---- title screen: title_tiles load at BG tile number 208 ---- */
#define TITLE_TILE_COUNT 35
extern const uint8_t title_tiles[];
extern const uint8_t title_map[18][20];
extern const uint8_t title_attr[18][20];

#endif
